# Docker compose to stand up all skema services in one file.
# Not standing up img2mml
version: "3.9"

services:
  Code2FN:
    image: code2fn:latest
    build:
      context: .
      dockerfile: Dockerfile.code2fn
    container_name: Code2FN
    ports:
      - "8002:8000" # Change port mapping appropriately before deploying.
    command: [ "uvicorn", "server:app", "--host", "0.0.0.0" ]
  skema:
    build:
      context: ./skema/skema-rs/
      dockerfile: Dockerfile
    entrypoint: cargo run --release --bin skema_service -- --host 0.0.0.0 --db-host database
    ports:
      - "8085:8080"

  # We currently use Memgraph (in-memory graph database).
  database:
    image: "memgraph/memgraph-platform"
    ports:
      - "7687:7687"
      - "3000:3000"
      - "7444:7444"
    volumes:
      - mg_lib:/var/lib/memgraph
      - mg_log:/var/log/memgraph
      - mg_etc:/etc/memgraph
    environment:
      - MEMGRAPH="--log-level=TRACE"
    entrypoint: [ "/usr/bin/supervisord" ]
volumes:
  mg_lib:
  mg_log:
  mg_etc:
